server:
    port: 8081
    servlet:
        context-path: /api/v1
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tikgik_bank}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:123}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
      hibernate:
        ddl-auto: ${DB_DDL-AUTO:update}
      show-sql: ${DB_SHOW_SQL:true}
      properties:
          hibernate:
              dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
      open-in-view: false
  application:
    name: account
logging:
  level:
    web: debug