server:
  port: 8083
  servlet:
    context-path: /api/v1
logging:
  level:
    web: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/tikgik_bank_bank}
    url: ${DB_URL_BANK:jdbc:postgresql://localhost:5432/tikgik_bank_bank}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:123}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL-AUTO:update}
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    open-in-view: false
  application:
    name: bank
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  config:
    import: ${CONFIG_SERVER_URL:optional:configserver:http://localhost:8071/}
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest
#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#    profiles:
#      active:
#        - "qa"
#
#
#build:
#  version: "3.0"
#
#banks:
#  message: "Welcome to EazyBank banks related local APIs "
#  contactDetails:
#    name: "Dragos Lech - Developer"
#    email: "dragos@eazybank.com"
#  onCallSupport:
#    - (412) 419-3491
#    - (915) 382-19320