logging:
  level:
    web: debug
    live.tikgik.bank.eurekaserver: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: eurekaserver
  profiles:
    active: default
  config:
    import: ${CONFIG_SERVER_URL:optional:configserver:http://localhost:8071/}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest