services:
  network-deploy-service:
    networks:
      - tikgikBank

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
      RABBIT_MQ_HOST: "rabbit"
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.11.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "broker:9092"
      KAFKA_BROKER: "broker:9092"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      broker:
        condition: service_started
#      rabbit:
#        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      CONFIG_SERVER_URL: configserver:http://configserver:8071/
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      EUREKA_SERVER_URL: http://eurekaserver:8070/eureka/
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: 123

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/