server:
  port: 8082
  servlet:
    context-path: /api/v1
logging:
  level:
    web: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tikgik_bank_loan}
#    url: ${DB_URL_LOAN:jdbc:postgresql://localhost:5432/tikgik_bank_loan}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:123}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL-AUTO:update}
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    open-in-view: false
  application:
    name: loan
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest
#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#    profiles:
#      active:
#        - "qa"
#
#
#build:
#  version: "3.0"
#
#loans:
#  message: "Welcome to EazyBank loans related local APIs "
#  contactDetails:
#    name: "Amaal Grega - Developer"
#    email: "amaal@eazybank.com"
#  onCallSupport:
#    - (452) 456-2176
#    - (546) 764-8934