# banks-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banks-deployment
  labels:
    app: banks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banks
  template:
    metadata:
      labels:
        app: banks
    spec:
      containers:
      - name: banks
        image: docker.io/khames96/bank:s10
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: tikgikbank-configmap
              key: BANKS_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: tikgikbank-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: tikgikbank-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: tikgikbank-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: tikgikbank-configmap
              key: DB_URL_BANK
        - name: DB_URL_BANK
          valueFrom:
            configMapKeyRef:
              name: tikgikbank-configmap
              key: DB_URL_BANK
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: spring-datasource-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: spring-datasource-password
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8083
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8083
        #   initialDelaySeconds: 20
        #   periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: banks
spec:
  selector:
    app: banks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
